import React, { useState, useEffect } from 'react';
import { Activity, Crown, Plus, Sparkles, Trash2, Zap } from 'lucide-react';
import { AI_TIMEOUT_SEC, ANSWER_STYLE_INSTRUCTIONS, ANSWER_STYLE_OPTIONS, CREDIT_API_TIMEOUT_MS, EXTENSION_SCRAPE_TIMEOUT_MS, withTimeout } from '../../answerStudio';
import { getAccessToken } from '../../auth';
import { ANSWER_STUDIO_MODEL, API_URL } from '../../config';
import { creditManager } from '../../creditManager';
import { getExtensionId, hasExtensionRuntime, sendToExtension } from '../../extensionClient';
import { DEFAULT_PROFILE } from '../../profileDefaults';
import { getActiveLegacyProfile, loadProfileStore, saveLegacyUserProfile } from '../../profileStore';
import ProfileSwitcher from '../shared/ProfileSwitcher';
import FabricationNotice, { loadFabricationCorpus } from '../shared/FabricationNotice';
import { log as baseLog } from '../../logger';

const log = baseLog.child('ui');

// --- VAULT PAGE (Answer Studio — Groq/Llama via POST /api/answer-vault/generate) ---
/**
 * "Answer Studio" tab — save reusable application answers and improve them
 * with AI.
 *
 * Generation posts to /api/answer-vault/generate (Groq/Llama). Job context is
 * scraped from the user's active tab via SCRAPE_ACTIVE_TAB, or typed in by
 * hand; without either, the answer is generated untailored and the user is
 * told so.
 *
 * Credit rule: one credit is deducted per *first* generation for an answer and
 * buys three follow-up improvements (`remainingImprovements`), which are free.
 * Premium accounts skip deduction entirely. Credits are deducted only after a
 * successful generation, so a failed call costs nothing.
 *
 * @param {object} props
 * @param {(message: string, type?: 'success'|'error'|'loading') => void} props.showToast
 * @param {object|null} props.user Supabase user; generation requires one.
 */
const VaultPage = ({ showToast, user }) => {
  const normalizeVaultItems = (items = []) =>
    (Array.isArray(items) ? items : []).map((item) => ({
      ...item,
      aiImprovementsLeft: Number.isFinite(Number(item?.aiImprovementsLeft))
        ? Math.max(0, Number(item.aiImprovementsLeft))
        : 0,
    }));

  const [profile, setProfile] = useState(DEFAULT_PROFILE);
  const [tempItem, setTempItem] = useState({ question: '', answer: '' });
  const [activeVaultItemId, setActiveVaultItemId] = useState(null);
  const [manualCompany, setManualCompany] = useState('');
  const [manualJobDescription, setManualJobDescription] = useState('');
  const [answerStyle, setAnswerStyle] = useState('balanced');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState('');
  const [fabricationFlags, setFabricationFlags] = useState([]);
  const [hasAutoGeneratedOnce, setHasAutoGeneratedOnce] = useState(false);
  const [remainingImprovements, setRemainingImprovements] = useState(0);
  const [credits, setCredits] = useState(null);
  const [creditsError, setCreditsError] = useState(null);
  const [premiumStatus, setPremiumStatus] = useState(false);
  const hasChrome = hasExtensionRuntime();

  const syncProfileToExtension = async (profilePayload) => {
    if (!hasChrome) return;
    const extId = getExtensionId();
    if (!extId) return;
    await new Promise((resolve) => {
      chrome.runtime.sendMessage(
        extId,
        {
          type: 'ONEXTAP_SYNC_DATA',
          payload: profilePayload,
        },
        () => {
          // Keep UI responsive even if extension sync fails.
          resolve();
        }
      );
    });
  };

  const loadCredits = async () => {
    setCreditsError(null);
    try {
      const { credits: c, isPremium: isPrem, error } = await creditManager.getCreditsWithStatus();
      setPremiumStatus(isPrem);
      if (error) {
        setCreditsError(error);
        setCredits(null);
      } else {
        setCredits(isPrem ? Infinity : (c ?? 0));
      }
    } catch (e) {
      setCreditsError(e?.message || 'Failed to load credits');
      setCredits(null);
    }
  };

  useEffect(() => {
    const load = async () => {
      await loadProfileStore();
      const saved = await getActiveLegacyProfile();
      if (saved) {
        setProfile({
          ...DEFAULT_PROFILE,
          ...saved,
          vault: normalizeVaultItems(saved.vault ?? DEFAULT_PROFILE.vault),
        });
      }
      await loadCredits();
    };
    load();
  }, []);

  const saveVault = async (newVault) => {
    const newProfile = { ...profile, vault: normalizeVaultItems(newVault) };
    setProfile(newProfile);
    await saveLegacyUserProfile(newProfile);
    await syncProfileToExtension(newProfile);
    setTempItem({ question: '', answer: '' });
    setActiveVaultItemId(null);
    setHasAutoGeneratedOnce(false);
    setRemainingImprovements(0);
    setFabricationFlags([]);
  };

  const handleAdd = () => {
    const q = (tempItem.question || '').trim();
    const a = (tempItem.answer || '').trim();
    const qLower = q.toLowerCase();
    const aLower = a.toLowerCase();
    const isDuplicate = (profile.vault || []).some(
      (item) =>
        (item.question || '').trim().toLowerCase() === qLower ||
        (item.answer || '').trim().toLowerCase() === aLower
    );
    if (!activeVaultItemId && isDuplicate) {
      showToast?.('Answer exists', 'error');
      return;
    }
    if (activeVaultItemId) {
      const updatedVault = (profile.vault || []).map((item) =>
        item.id === activeVaultItemId
          ? {
              ...item,
              question: q,
              answer: a,
              aiImprovementsLeft: premiumStatus ? 0 : remainingImprovements,
            }
          : item
      );
      saveVault(updatedVault);
      showToast?.('Saved changes', 'success');
      return;
    }
    saveVault([
      ...(profile.vault || []),
      {
        id: Date.now(),
        question: q,
        answer: a,
        aiImprovementsLeft: premiumStatus ? 0 : remainingImprovements,
      },
    ]);
    showToast?.('Added to vault', 'success');
  };

  const loadVaultItemToEditor = (item) => {
    setActiveVaultItemId(item.id);
    setTempItem({
      question: String(item.question || ''),
      answer: String(item.answer || ''),
    });
    setRemainingImprovements(premiumStatus ? 0 : Math.max(0, Number(item.aiImprovementsLeft || 0)));
    setHasAutoGeneratedOnce(true);
    setGenerateError('');
    setFabricationFlags([]);
    showToast?.('Loaded saved answer into editor', 'success');
  };

  const persistActiveItemState = async (nextAnswer, nextImprovements) => {
    if (!activeVaultItemId) return;
    const updatedVault = (profile.vault || []).map((item) =>
      item.id === activeVaultItemId
        ? {
            ...item,
            answer: nextAnswer,
            aiImprovementsLeft: premiumStatus ? 0 : Math.max(0, Number(nextImprovements || 0)),
          }
        : item
    );
    const newProfile = { ...profile, vault: normalizeVaultItems(updatedVault) };
    setProfile(newProfile);
    await saveLegacyUserProfile(newProfile);
    await syncProfileToExtension(newProfile);
  };

  const handleImproveWithAI = async () => {
    const q = (tempItem.question || '').trim();
    if (!q) {
      setGenerateError('Enter a question first.');
      return;
    }

    let latestCredits = credits;
    if (!premiumStatus && latestCredits === null) {
      try {
        const { credits: fetchedCredits, error } = await creditManager.getCreditsWithStatus();
        if (!error && Number.isFinite(fetchedCredits)) {
          latestCredits = fetchedCredits;
          setCredits(fetchedCredits);
        }
      } catch {
        // Fall through; normal generation flow will still show server errors if any.
      }
    }
    const consumesCredit = !premiumStatus && remainingImprovements <= 0;
    if (consumesCredit && Number(latestCredits || 0) <= 0) {
      setGenerateError('No credits remaining.');
      showToast?.('No credits remaining. Upgrade to continue.', 'error');
      return;
    }

    setIsGenerating(true);
    setGenerateError('');
    setFabricationFlags([]);
    showToast?.('AI is thinking...', 'loading');

    try {
      // Get job context from extension (SCRAPE_ACTIVE_TAB)
      let company = '';
      let description = '';
      if (hasChrome) {
        try {
          const scrapeRes = await withTimeout(
            sendToExtension('SCRAPE_ACTIVE_TAB'),
            EXTENSION_SCRAPE_TIMEOUT_MS,
            'Timed out reading job listing from extension. Try again.'
          );
          if (scrapeRes?.success && scrapeRes?.context) {
            company = scrapeRes.context.company || '';
            description = scrapeRes.context.description || '';
          }
        } catch (e) {
          log.warn('Could not scrape job page:', e);
        }
      }
      const manualDescription = (manualJobDescription || '').trim();
      const manualCompanyName = (manualCompany || '').trim();
      const contextDescription = manualDescription || (description || '').trim();
      const hasJobContext = !!contextDescription;
      const jdSnippet = hasJobContext ? String(contextDescription).substring(0, 6000) : '';
      const companyName = (manualCompanyName || company || 'Not specified').trim();
      const userAnswer = (tempItem.answer || '').trim();
      const hasGeneric = userAnswer.length > 0;
      const profileSkills = (profile.skills || [])
        .map((s) => String(s || '').trim())
        .filter(Boolean)
        .slice(0, 8)
        .join(', ');
      const currentRole = [profile.currentJob?.title, profile.currentJob?.company]
        .map((v) => String(v || '').trim())
        .filter(Boolean)
        .join(' at ');
      const recentExperience = (profile.experience || [])
        .filter((ex) => (ex?.title || ex?.company))
        .slice(0, 2)
        .map((ex) => {
          const title = String(ex?.title || '').trim();
          const org = String(ex?.company || '').trim();
          return [title, org].filter(Boolean).join(' at ');
        })
        .filter(Boolean)
        .join(' | ');
      const profileLines = [
        currentRole ? `Current role: ${currentRole}` : '',
        profileSkills ? `Core skills: ${profileSkills}` : '',
        recentExperience ? `Recent experience: ${recentExperience}` : '',
      ].filter(Boolean);
      const profileContext = profileLines.length
        ? profileLines.join('\n')
        : '';
      const selectedStyleInstruction =
        ANSWER_STYLE_INSTRUCTIONS[answerStyle] || ANSWER_STYLE_INSTRUCTIONS.balanced;
      const richerLengthRule = 'Target length: 170-240 words unless the question clearly needs less.';
      const measurableImpactRule =
        'Include at least one measurable or observable impact/result. Prefer numbers/percentages/timeframes when truthful; never invent facts.';

      const jobContext = hasJobContext
        ? `${companyName ? `Company: ${companyName}\n\n` : ''}${jdSnippet}`
        : '';

      const vaultAnswers = (profile.vault || []).map((item) => ({
        question: String(item.question || ''),
        answer: String(item.answer || ''),
      }));

      let taskHint = '';
      if (hasGeneric) {
        taskHint = hasJobContext
          ? `Rewrite the candidate draft to target the job description and company. Answer the application question directly. Tone: human, natural, confident. ${richerLengthRule} First person. At least two concrete details tied to the role; weave in 2-4 phrases from the job description. ${measurableImpactRule} No filler, cliches, headings, or bullet points.`
          : `Improve the candidate draft so it is stronger and clearer. Answer the application question directly. Preserve the candidate's intent; add specificity and one concrete example or outcome. ${richerLengthRule} First person. ${measurableImpactRule} No filler, cliches, headings, or bullet points.`;
      } else {
        taskHint = hasJobContext
          ? `Write a tailored answer to the application question. Use the job description and company to ground specifics. ${richerLengthRule} First person. At least two concrete details; reflect 2-4 ideas from the job description. ${measurableImpactRule} Interview-ready, not a template. No filler, cliches, headings, or bullet points.`
          : `Write a strong, portable first-draft answer that works across employers. Target length: 160-230 words unless the question clearly needs less. First person. At least one concrete skill and one measurable or observable result. ${measurableImpactRule} Specific enough to sound real; broadly reusable. No filler, cliches, headings, or bullet points.`;
      }

      const token = await getAccessToken();
      if (!token) throw new Error('Please sign in first.');

      // The active resume, if there is one. Sending it turns on the server's
      // deterministic fabrication check; omitting it leaves the call exactly as
      // it was before that check existed.
      const corpus = await loadFabricationCorpus();

      const requestBody = {
        question: q,
        draft: userAnswer,
        jobContext: jobContext || 'Not provided',
        vaultAnswers,
        ...(profileContext ? { profileContext } : {}),
        taskHint,
        styleHint: selectedStyleInstruction,
        model: ANSWER_STUDIO_MODEL,
        ...(corpus.length ? { corpus } : {}),
      };

      const generatePromise = fetch(`${API_URL}/api/answer-vault/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(requestBody),
      }).then(async (res) => {
        const body = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(body?.error || `Generation failed (${res.status})`);
        return body;
      });

      const result = await withTimeout(
        generatePromise,
        AI_TIMEOUT_SEC * 1000,
        'AI is taking too long. Check your connection and try again.'
      );
      const improvedText = String(result?.text || '').trim();
      // Empty only. There used to be an `improvedText.includes('Error')` guard
      // here, which rejected any answer containing that substring anywhere:
      // "error budgets", "error rates", "error handling" — exactly the answers
      // an SRE or backend candidate needs the Answer Studio to write. It also
      // threw `improvedText` itself as the message, so a perfectly good answer
      // was shown to the user as an error toast.
      //
      // A failed generation is already caught upstream: the fetch above throws
      // on a non-2xx, and a model that returns prose about errors is returning
      // an answer, not an error.
      if (!improvedText) {
        throw new Error('The model returned an empty answer. Try again.');
      }

      if (!hasJobContext) {
        showToast?.('Generated without job-page context. Open a job listing and click Improve again to tailor it.', 'error');
      } else if (manualDescription) {
        showToast?.('Generated using pasted job description context.', 'success');
      }

      setTempItem(prev => ({ ...prev, answer: improvedText }));
      setHasAutoGeneratedOnce(true);
      // Advisory only — the answer stands and no credit is spent on a retry the
      // user did not ask for. See FabricationNotice.
      setFabricationFlags(Array.isArray(result?.fabricationFlags) ? result.fabricationFlags : []);

      if (!premiumStatus) {
        let nextImprovements = remainingImprovements;
        if (consumesCredit) {
          // 1 credit purchases one generation + up to 3 subsequent improvements.
          try {
            const deductResult = await withTimeout(
              creditManager.deductCredit(),
              CREDIT_API_TIMEOUT_MS,
              'Credit update timed out after generation.'
            );
            if (!deductResult.success) {
              setGenerateError(deductResult.error || 'Answer generated, but credits could not be updated.');
              setRemainingImprovements(0);
              nextImprovements = 0;
            } else {
              setCredits(deductResult.isPremium ? Infinity : deductResult.remaining);
              setRemainingImprovements(3);
              nextImprovements = 3;
            }
          } catch (creditErr) {
            log.warn('Credit deduction failed after generation:', creditErr);
            setGenerateError('Answer generated, but credit update failed. Please refresh credits.');
            setRemainingImprovements(0);
            nextImprovements = 0;
          }
        } else {
          nextImprovements = Math.max(0, remainingImprovements - 1);
          setRemainingImprovements(nextImprovements);
        }
        try {
          await persistActiveItemState(improvedText, nextImprovements);
        } catch (persistErr) {
          log.warn('Could not persist AI improvement balance:', persistErr);
        }
      }

      showToast?.('AI answer generated!', 'success');
    } catch (e) {
      setGenerateError(e?.message || 'Something went wrong.');
      showToast?.(e?.message || 'AI generation failed', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const canImprove = !!user && !!tempItem.question?.trim();

  const reloadVaultProfile = async () => {
    const saved = await getActiveLegacyProfile();
    if (saved) {
      setProfile({
        ...DEFAULT_PROFILE,
        ...saved,
        vault: normalizeVaultItems(saved.vault ?? DEFAULT_PROFILE.vault),
      });
    }
  };

  return (
    <div className="animate-fade-in max-w-3xl mx-auto space-y-6">
      <ProfileSwitcher onProfileChange={reloadVaultProfile} />
      {/* Header card */}
      <div className="bg-white/80 backdrop-blur-sm rounded-3xl border border-onextap-primary/15 p-8 shadow-lg shadow-onextap-dark/5 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl from-onextap-primary/10 to-transparent rounded-full blur-2xl" />
        
        <div className="relative z-10">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="font-bold text-2xl text-onextap-dark tracking-tight mb-1">Answer Studio</h2>
              <p className="text-onextap-dark/60 text-sm">Create and improve your job application answers</p>
            </div>
            <div className="flex items-center gap-2">
              {/* Credits badge */}
              {credits !== null && (
                <div className={`flex items-center gap-1.5 px-3 py-2 rounded-2xl text-sm font-medium border shadow-sm ${
                  premiumStatus 
                    ? 'bg-gradient-to-r from-amber-50 to-amber-100/50 text-amber-700 border-amber-200'
                    : credits === 0 
                      ? 'bg-red-50 text-red-600 border-red-200'
                      : 'bg-onextap-primary/10 text-onextap-dark border-onextap-primary/20'
                }`}>
                  {premiumStatus ? (
                    <><Crown size={14} /> Premium</>
                  ) : (
                    <><Zap size={14} /> {credits} credits left</>
                  )}
                </div>
              )}
              {user && !premiumStatus && (
                <div className="flex items-center gap-2 px-4 py-2 rounded-2xl text-sm font-medium bg-gradient-to-r from-onextap-primary/15 to-onextap-primary/5 text-onextap-primary border border-onextap-primary/25 shadow-sm">
                  <Sparkles size={14} />
                  Standard AI
                </div>
              )}
            </div>
          </div>
          
          <div className="bg-gradient-to-br from-white to-onextap-bg-light p-6 rounded-2xl border border-onextap-primary/15 shadow-sm">
            <input 
              className="w-full px-4 py-3 mb-3 border border-onextap-primary/20 rounded-xl text-sm bg-white/80 focus:outline-none focus:border-onextap-primary/40 focus:ring-2 focus:ring-onextap-primary/10 transition-all placeholder:text-onextap-dark/40" 
              placeholder="Question (e.g. Why do you want to work here?)"
              value={tempItem.question}
              onChange={e => {
                setTempItem({ ...tempItem, question: e.target.value });
                setGenerateError('');
                if (!activeVaultItemId) {
                  setHasAutoGeneratedOnce(false);
                  setRemainingImprovements(0);
                }
              }}
            />
            <input
              className="w-full px-4 py-3 mb-3 border border-onextap-primary/20 rounded-xl text-sm bg-white/80 focus:outline-none focus:border-onextap-primary/40 focus:ring-2 focus:ring-onextap-primary/10 transition-all placeholder:text-onextap-dark/40"
              placeholder="Company (optional, manual override)"
              value={manualCompany}
              onChange={e => { setManualCompany(e.target.value); setGenerateError(''); }}
            />
            <textarea
              className="w-full px-4 py-3 mb-3 border border-onextap-primary/20 rounded-xl text-sm h-24 bg-white/80 focus:outline-none focus:border-onextap-primary/40 focus:ring-2 focus:ring-onextap-primary/10 transition-all resize-none placeholder:text-onextap-dark/40"
              placeholder="Paste job description here (optional). If provided, this is used for tailoring."
              value={manualJobDescription}
              onChange={e => { setManualJobDescription(e.target.value); setGenerateError(''); }}
            />
            <select
              className="w-full px-4 py-3 mb-3 border border-onextap-primary/20 rounded-xl text-sm bg-white/80 focus:outline-none focus:border-onextap-primary/40 focus:ring-2 focus:ring-onextap-primary/10 transition-all"
              value={answerStyle}
              onChange={e => { setAnswerStyle(e.target.value); setGenerateError(''); }}
            >
              {ANSWER_STYLE_OPTIONS.map((option) => (
                <option key={option.value} value={option.value}>{option.label}</option>
              ))}
            </select>
            <textarea 
              className="w-full px-4 py-3 border border-onextap-primary/20 rounded-xl text-sm h-28 bg-white/80 focus:outline-none focus:border-onextap-primary/40 focus:ring-2 focus:ring-onextap-primary/10 transition-all resize-none placeholder:text-onextap-dark/40" 
              placeholder="Your answer (optional). Click Improve to generate or refine with AI."
              value={tempItem.answer}
              onChange={e => setTempItem({...tempItem, answer: e.target.value})}
            />
            <div className="mt-4 flex flex-wrap items-center gap-3">
              <button 
                disabled={!tempItem.question || !tempItem.answer}
                onClick={handleAdd}
                className="bg-onextap-dark text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-onextap-dark/90 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-md shadow-onextap-dark/20 hover:shadow-lg transition-all duration-200"
              >
                <Plus size={16} /> Add to Vault
              </button>
              <button 
                type="button"
                disabled={!canImprove || isGenerating}
                onClick={handleImproveWithAI}
                className="px-5 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2 bg-gradient-to-r from-onextap-primary/15 to-onextap-primary/5 text-onextap-dark border border-onextap-primary/25 hover:from-onextap-primary/25 hover:to-onextap-primary/10 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-sm"
              >
                {isGenerating ? <Activity className="animate-spin" size={16} /> : <Sparkles size={16} />}
                {isGenerating
                  ? (tempItem.answer?.trim() ? 'Improving…' : 'Generating…')
                  : (!tempItem.answer?.trim() ? 'Generate answer' : hasAutoGeneratedOnce ? 'Improve answer' : 'Generate answer')}
              </button>
              <span className="text-xs text-onextap-dark/50">
                Mode: {premiumStatus ? 'High Quality (Premium)' : 'Standard (Faster)'}
              </span>
              {!premiumStatus && (
                <span className="text-xs text-onextap-dark/50">
                  Free improvements left on this answer: {remainingImprovements}
                </span>
              )}
            </div>
            <div className="mt-3 text-xs text-onextap-dark/55 bg-onextap-primary/5 px-3 py-2 rounded-lg border border-onextap-primary/15">
              Credit rules: 1 credit generates 1 answer and includes 3 free improvements for that saved answer. Free improvements persist per saved answer across page reloads.
            </div>
            {creditsError && (
              <div className="mt-3 text-sm text-amber-700 bg-amber-50 px-3 py-2 rounded-lg border border-amber-200">
                Couldn't load credits: {creditsError}
                <p className="text-xs mt-1">
                  Check the message above, then: server running (<code className="text-[11px]">npm run dev</code> in <code className="text-[11px]">server/</code>),
                  <code className="text-[11px]"> VITE_API_URL</code> pointing at it, and <code className="text-[11px]">SUPABASE_URL</code> + <code className="text-[11px]">SUPABASE_SERVICE_ROLE_KEY</code> in <code className="text-[11px]">server/.env</code>.
                </p>
                <button onClick={loadCredits} className="mt-2 text-sm font-medium text-amber-800 underline hover:no-underline">Try again</button>
              </div>
            )}
            {generateError && <p className="mt-3 text-sm text-red-600 bg-red-50 px-3 py-2 rounded-lg">{generateError}</p>}
            {!isGenerating && <FabricationNotice flags={fabricationFlags} className="mt-3" />}
            {hasChrome && (
              <p className="mt-3 text-xs text-onextap-dark/50 bg-onextap-primary/5 px-3 py-2 rounded-lg">
                <Sparkles size={10} className="inline mr-1" />
                AI uses pasted JD first, otherwise it tries current/recent job tabs and your saved profile strengths.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Saved answers */}
      {profile.vault && profile.vault.length > 0 && (
        <div className="space-y-4">
          <h3 className="font-bold text-lg text-onextap-dark px-1">Saved Answers ({profile.vault.length})</h3>
          <div className="space-y-3">
            {profile.vault.map(item => (
              <div key={item.id} className="bg-white/70 backdrop-blur-sm border border-onextap-primary/15 rounded-2xl p-5 relative group hover:bg-white/90 hover:shadow-md transition-all duration-200">
                <button 
                  onClick={() => saveVault(profile.vault.filter(i => i.id !== item.id))} 
                  className="absolute top-4 right-4 p-2 text-onextap-dark/30 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all opacity-0 group-hover:opacity-100"
                >
                  <Trash2 size={16} />
                </button>
                <h4 className="font-bold text-onextap-dark text-sm mb-2 pr-10">{item.question}</h4>
                <p className="text-onextap-dark/60 text-sm leading-relaxed">{item.answer}</p>
                <div className="mt-3 flex items-center justify-between gap-2">
                  {!premiumStatus && (
                    <span className="text-xs text-onextap-dark/50">
                      Free improvements left: {Math.max(0, Number(item.aiImprovementsLeft || 0))}
                    </span>
                  )}
                  <button
                    type="button"
                    onClick={() => loadVaultItemToEditor(item)}
                    className="text-xs font-medium px-2.5 py-1.5 rounded-lg border border-onextap-primary/20 text-onextap-primary hover:bg-onextap-primary/10 transition-colors"
                  >
                    Use in editor
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default VaultPage;
